apiVersion: v1
kind: Secret
metadata:
 name: env-secret
type: Opaque
data:
 credentials: YXdzX2FjY2Vzc19rZXlfaWQgPSBBU0lBM0E2SVNLQlVJWkJJWkQ1Tgphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBXQlV4NTVlK2l4Z0djNGE0MGJQVEwzOFUyN3FLSmpBYzhxVngwZFlFCmF3c19zZXNzaW9uX3Rva2VuPUZ3b0daWEl2WVhkekVCNGFES3hpV1ZMRGhGK0lPSks4MlNMVkFjcUZ2VlR1WDJwWFhEZ2VrZ2RONnpjeUQrTWhhRHhzay9EWWZsS2ZiQ1Z3U2E3MWR5NFRmMEtTbjJSNzB5Q0JEbmRoaUJSbTdVamRMZjY4dUd3bmdURnhzVXVxME92OFo4b0R2UkJtQWUreUR6dlQ4OXdLM2tGL0NPTituZzNwSE9PVHh3c0NUTXZsNE5iZ0VBcUprSWJ4eHZhUTFlRjR1TnZ1bTh0VEtrOXpVZW9Say9JK1Q3NEFPNG55Skd4Z0RvVXdwVWI1aUVEWVR2aS9CSVh1RGxrZzFiT3MxcFk4VlNUanh1Z3NtaG8yZC9MRVFwWnVlT21qS1UrM2ZvUDh2eVVLTCs4VjR3U3h0ZDYwaXRSd2oxWlI4NTJRN2lpZmhwK2lCakl0SlgxbUFIKzRncWdjQWd2Ukh5Slo0TkZNbm9LTWhabmZkWmVaWjYxckxEVkFpWC9oNWd5NXhkemtkUExo